server.port: 8080
server.request.encoding: utf-8
server.response.encoding: utf-8
server.http.ioBound: true
solon.threads.virtual.enabled: true

solon.app:
  name: udata-harness
  group: udata

solon.logging:
  appender:
    console:
      level: INFO


solon.config.load:
#  - "classpath:${solon.env}/*.yml" #v2.7.6 后支持 * 表达式   #只加载内部文件
  - "model.yml"                                             #先加载外部文件；如果没有则加载内部文件
  - "./model.yml"                                             #先加载外部文件；如果没有则加载内部文件



